export interface ModuleReference {
  text: string;  // APA citation text (supports *italic* for titles)
  url?: string;
  note?: string;
}

export const moduleReferences: Record<number, ModuleReference[]> = {
  1: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Clarivate. (2024). *Pulse of the library 2024.*",
      url: "https://doi.org/10.14322/pulse.of.the.library.2024",
    },
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
    {
      text: "*The New York Times Company v. Microsoft Corporation,* No. 1:23-cv-11195 (S.D.N.Y. filed Dec. 27, 2023).",
      note: "Legal citation follows Bluebook convention.",
    },
  ],

  2: [
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
  ],

  3: [
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
  ],

  4: [
    {
      text: "American Library Association. (2021). *ALA code of ethics.*",
      url: "https://www.ala.org/tools/ethics",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Association of Research Libraries. (2024). *Research libraries guiding principles for artificial intelligence.*",
      url: "https://www.arl.org/resources/research-libraries-guiding-principles-for-artificial-intelligence/",
    },
    {
      text: "*The New York Times Company v. Microsoft Corporation,* No. 1:23-cv-11195 (S.D.N.Y. filed Dec. 27, 2023).",
      note: "Legal citation follows Bluebook convention.",
    },
    {
      text: "U.S. Copyright Office. (2023, March 16). *Copyright registration guidance: Works containing material generated by artificial intelligence.* 88 Fed. Reg. 16190.",
      url: "https://www.copyright.gov/ai/ai_policy_guidance.pdf",
    },
    {
      text: "U.S. Copyright Office. (2025, January 29). *Copyright and artificial intelligence, Part 2: Copyrightability.*",
      url: "https://www.copyright.gov/ai/Copyright-and-Artificial-Intelligence-Part-2-Copyrightability-Report.pdf",
    },
  ],

  5: [
    {
      text: "Association of College and Research Libraries. (2016). *Framework for information literacy for higher education.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ilframework",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
  ],

  6: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
  ],

  7: [
    {
      text: "Association of College and Research Libraries. (2016). *Framework for information literacy for higher education.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ilframework",
    },
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
  ],

  8: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "OCLC. (2025, December). *AI-assisted cataloging in WorldShare Record Manager and Connexion.*",
      url: "https://www.oclc.org/en/worldshare-record-manager.html",
      note: "Confirm exact release note URL when updating the site.",
    },
  ],

  9: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Ex Libris. (2025). *Alma Specto: AI-powered digital collections management.* Clarivate.",
      url: "https://exlibrisgroup.com/products/alma-library-services-platform/",
    },
    {
      text: "Harvard Library. (2024). *Harvard Library Collections Explorer.* Harvard University.",
      url: "https://library.harvard.edu",
      note: "Confirm direct URL for the Collections Explorer.",
    },
    {
      text: "Yale University Library. (2024). *Digital collections AI application* [Prototype]. Yale University.",
      url: "https://library.yale.edu",
      note: "Confirm direct URL for the Yale digital collections AI application.",
    },
  ],

  10: [
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
  ],

  11: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "Clarivate. (2024). *Pulse of the library 2024.*",
      url: "https://doi.org/10.14322/pulse.of.the.library.2024",
    },
    {
      text: "Clarivate. (2025). *Pulse of the library 2025.*",
      url: "https://clarivate.com/pulse-of-the-library/",
    },
  ],

  12: [
    {
      text: "Dakan, R., & Feller, A. (2025). *AI fluency: Framework & foundations* [Online course]. Anthropic Academy.",
      url: "https://anthropic.skilljar.com/ai-fluency-framework-foundations",
    },
  ],

  13: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
  ],

  14: [
    {
      text: "Karpathy, A. [@karpathy]. (2025, February 2). There's a new kind of coding I call \"vibe coding\" [Post]. X (formerly Twitter).",
      url: "https://x.com/karpathy/status/1886192184808149383",
    },
    {
      text: "Michalak, R., Dawes, T. A., & Wallace, A. (2026, May). Envisioning AI's role in libraries: Perspectives from an LIS student, a library director, and a university librarian. *College & Research Libraries News, 87*(5).",
      url: "https://crln.acrl.org/index.php/crlnews/article/view/27321",
      note: "Note: Module text attributes separate passages to \"Ava Wallace\" and \"Trevor A. Dawes\" individually. Both passages originate from this co-authored article; in-text attributions should be updated to cite all three authors or use (Michalak et al., 2026).",
    },
  ],

  15: [
    {
      text: "Ex Libris. (2025). *Alma library services platform.* Clarivate.",
      url: "https://exlibrisgroup.com/products/alma-library-services-platform/",
    },
    {
      text: "Ex Libris. (2025). *LibOW: Low-code automation for Alma.* Clarivate.",
      url: "https://exlibrisgroup.com/blog/what-is-libow/",
    },
  ],

  16: [
    {
      text: "Association of College and Research Libraries. (2025, October). *AI competencies for academic library workers.* American Library Association.",
      url: "https://www.ala.org/acrl/standards/ai",
    },
    {
      text: "ALA TechSource. (n.d.). *Library technology reports.* American Library Association.",
      url: "https://www.ala.org/pubs/periodicals/ltr",
    },
    {
      text: "Association of Research Libraries. (n.d.). *ALA Core: Library and information technology association.* American Library Association.",
      url: "https://www.ala.org/core/",
    },
    {
      text: "Clarivate. (2025). *Pulse of the library 2025.*",
      url: "https://clarivate.com/pulse-of-the-library/",
    },
    {
      text: "Michalak, R., Dawes, T. A., & Wallace, A. (2026, May). Envisioning AI's role in libraries: Perspectives from an LIS student, a library director, and a university librarian. *College & Research Libraries News, 87*(5).",
      url: "https://crln.acrl.org/index.php/crlnews/article/view/27321",
    },
  ],
};
